alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table ActualJob drop constraint FKsrs2gdr2erivq4q4f85y5ls7v
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
alter table Message drop constraint FK6p3nfecpdhqemc3956wom1qbl
alter table Message drop constraint FKk97pu7g6klvlih8xb75xb5m7p
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
alter table Student drop constraint FKcgqfnhy6eu7j1bg0mrcon06hh
drop table if exists ActualJob cascade
drop table if exists Klass cascade
drop table if exists Message cascade
drop table if exists School cascade
drop table if exists Student cascade
drop table if exists Workplace cascade
